# Generated by Django 4.1.7 on 2023-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("national_id", models.IntegerField()),
                ("birth_date", models.DateField()),
                ("address", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=30)),
                ("finger_print_signature", models.CharField(max_length=200)),
            ],
        ),
    ]
