# Generated by Django 4.1.7 on 2023-03-06 13:07

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercsvfile",
            name="state",
            field=django_fsm.FSMField(
                default="uploading", max_length=50, protected=True
            ),
        ),
    ]
